store/catalog/urls.py
from django.urls import path

from . import views

app_name = 'catalog'

urlpatterns = [
    path('', views.Catalog.as_view(), name='catalog'),
    path('sub_catalog/<str:sub_catalog_name>/<str:current_item_type>/<str:prev_item_type>/',
         views.sub_catalog, name='sub_catalog'),
    path('item/<int:item_id>/<str:sub_catalog_name>/', views.item, name='item'),
]

store/home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.start, name='start'),
    path('section/<str:section_name>/<str:previous_section>/', views.section, name='section'),
]

store/store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('users/', include('users.urls')),
    path('catalog/', include('catalog.urls')),
    path('service/', include('service.urls')),
    path('car_wash/', include('car_wash.urls')),
    path('contacts/', include('contacts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/catalog/models.py
from django.db import models
from django.db.models import SET_NULL, PROTECT

from catalog.constants import HEAD, DUMP, CARGO, LIGHT, BRAKES, ENGINE

NULLABLE = {'null': True, 'blank': True}


class SubCatalog(models.Model):
    name = models.CharField(max_length=20, verbose_name='Name')
    label = models.CharField(max_length=20, verbose_name='Label')
    img = models.CharField(max_length=200)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Sub catalog'
        verbose_name_plural = 'Sub catalogs'
        ordering = ('-name',)


class Truck(models.Model):

    TRUCKS_TYPES = [
        (HEAD, 'head'),
        (CARGO, 'cargo'),
        (DUMP, 'dump'),
    ]

    name = models.CharField(max_length=50)
    price = models.IntegerField()
    info = models.OneToOneField('TruckInfo', on_delete=SET_NULL, **NULLABLE, related_name='truck')
    sub_catalog = models.ForeignKey('SubCatalog', on_delete=PROTECT, related_name='truck_sub_catalog')
    type = models.CharField(max_length=10, choices=TRUCKS_TYPES, **NULLABLE)
    main_photo = models.ImageField(upload_to='trucks_img/')
    second_photo = models.ImageField(upload_to='trucks_img/', **NULLABLE)
    third_photo = models.ImageField(upload_to='trucks_img/', **NULLABLE)
    create_date = models.DateField(auto_now_add=True)
    change_date = models.DateField(auto_now=True)

    def __str__(self):
        return f'{self.name} {self.type}'

    def show_id(self):
        return f'{self.pk:05}'

    class Meta:
        verbose_name = 'Truck'
        verbose_name_plural = 'Trucks'
        ordering = ('pk',)


class TruckInfo(models.Model):

    class Condition(models.IntegerChoices):
        BRAND_NEW = 0, 'brand new'
        USED = 1, 'used'

    year = models.IntegerField(**NULLABLE)
    mileage = models.IntegerField(**NULLABLE)
    power = models.IntegerField(**NULLABLE)
    condition = models.BooleanField(choices=Condition.choices)
    discount = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'TruckInfo'
        verbose_name_plural = 'TruckInfo'


class Part(models.Model):

    PARTS_TYPES = [
        (LIGHT, 'light'),
        (ENGINE, 'engine'),
        (BRAKES, 'brakes'),
    ]

    name = models.CharField(max_length=50)
    price = models.IntegerField()
    info = models.TextField(**NULLABLE)
    sub_catalog = models.ForeignKey('SubCatalog', on_delete=PROTECT, related_name='part_sub_catalog')
    type = models.CharField(max_length=10, choices=PARTS_TYPES, **NULLABLE)
    main_photo = models.ImageField(upload_to='parts_img/')
    create_date = models.DateField(auto_now_add=True)
    change_date = models.DateField(auto_now=True)

    class Meta:
        verbose_name = 'Part'
        verbose_name_plural = 'Parts'
        ordering = ('pk',)

store/catalog/views.py
from django.core.paginator import Paginator
from django.shortcuts import render
from django.views import View
from django.views.generic import TemplateView

from catalog.constants import ITEMS_TYPES_DATA, SUB_CATALOG_CONTEXT, SUB_CATALOG_TEMPLATES
from catalog.models import Truck, Part
from catalog.templatetags.catalog_tags import get_catalog_items


def catalog(request):
    return render(request, 'catalog/catalog.html')


class Catalog(TemplateView):
    template_name = 'catalog/catalog.html'


def sub_catalog(request, sub_catalog_name, current_item_type, prev_item_type):
    # current_item_type = request.GET.get('current_item_type', 'all types')
    # prev_item_type = request.GET.get('prev_item_type', 'all types')
    page = request.GET.get('page', 1)
    items = get_catalog_items(sub_catalog_name, current_item_type)
    paginator = Paginator(items, 6)
    current_page = paginator.page(int(page))

    context = {
        'sub_catalog_name': sub_catalog_name,
        'types_data': ITEMS_TYPES_DATA[sub_catalog_name],
        'current_item_type': current_item_type,
        'prev_item_type': prev_item_type,
        'items': current_page,
    }
    return render(request, 'catalog/sub_catalog.html', {**context, **SUB_CATALOG_CONTEXT})


def item(request, item_id, sub_catalog_name):
    CATALOG_TABLES = {'trucks': Truck, 'parts': Part}
    catalog_item = CATALOG_TABLES[sub_catalog_name].objects.get(pk=item_id)
    context = {
        'item': catalog_item,
    }
    return render(request, SUB_CATALOG_TEMPLATES[sub_catalog_name], {**context, **SUB_CATALOG_CONTEXT})

store/catalog/templates/catalog/includes/call_us.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'css/call_us.css' %}">

<div class="call-us">
    <img class="call-icon" src="{% static 'img/call.svg' %}" alt="phone icon">
    <div class="call-text">
        <p class="call-message">Have questions? <br>Contact us!</p>
        <p class="call-phone">Phone:<br>8-888-888-88-88</p>
    </div>
</div>

store/catalog/templates/catalog/includes/container_item.html
{% load catalog_tags %}

<a class="item-link" href="{% url 'catalog:item' item.pk sub_catalog_name %}">
    <div class="store_item" style='background-image:url("{% main_photo_path_tag item %}")'>
        <div class="info_background"></div>

        {% if sub_catalog_name == 'trucks' %}
            <p class="item_name">{{ item.name }} {{ item.info.year }}</p>
        {% elif sub_catalog_name == 'parts' %}
            <p class="item_name">{{ item.name }}</p>
        {% endif %}

        {% if item.price > 0 %}
            <p class="item_price">price: {{ item.price }} EUR </p>
        {% else %}
            <p class="item_price">price on request</p>
        {% endif %}
    </div>
</a>

store/catalog/templates/catalog/includes/item_in_list.html
{% load catalog_tags %}
<a class="item-link" href="{% url 'catalog:item' item.pk sub_catalog_name %}">
    <div class="store_item" style='background-image:url("{% main_photo_path_tag item %}")'>
        <div class="info_background"></div>

        {% if sub_catalog_name == 'trucks' %}
            <p class="item_name">{{ item.name }} {{ item.info.year }}</p>
        {% elif sub_catalog_name == 'parts' %}
            <p class="item_name">{{ item.name }}</p>
        {% endif %}

        {% if item.price > 0 %}
            <p class="item_price">price: {{ item.price }} EUR</p>
        {% else %}
            <p class="item_price">price on request</p>
        {% endif %}
    </div>
</a>

store/catalog/templates/catalog/includes/items_list.html
<a class="item-link" href="{% url 'catalog:item' item.pk sub_catalog_name %}">
    <div class="store_item" style='background-image:url("{{item.main_photo.url}}")'>
        <div class="info_background"></div>

        {% if sub_catalog_name == 'trucks' %}
            <p class="item_name">{{ item.name }} {{ item.info.year }}</p>
        {% elif sub_catalog_name == 'parts' %}
            <p class="item_name">{{ item.name }}</p>
        {% endif %}

        {% if item.price > 0 %}
            <p class="item_price">price: {{ item.price }} EUR</p>
        {% else %}
            <p class="item_price">price on request</p>
        {% endif %}
    </div>
</a>

store/catalog/templates/catalog/includes/pagination.html
<div class="pagination">
    {% if items.has_previous %}
        <a href="?page={{ items.previous_page_number }}"><div class="prev-page">prev</div></a>
    {% else %}
       <div class="prev-page disabled">prev</div>
    {% endif %}

    {% for page in items.paginator.page_range %}
        {% if page >= items.number|add:"-2" and page <= items.number|add:"2" %}
            {% if items.number == page %}
                <div class="page-link disabled">{{ page }}</div>
            {% else %}
                <a href="?page={{ page }}"><div class="page-link">{{ page }}</div></a>
            {% endif %}
        {% endif %}
    {% endfor %}

    {% if items.has_next %}
        <a href="?page={{ items.next_page_number }}"><div class="next-page">next</div></a>
    {% else %}
        <div class="next-page disabled">next</div>
    {% endif %}
</div>