store/catalog/urls.py
from django.urls import path

from . import views

app_name = 'catalog'

urlpatterns = [
    path('', views.Catalog.as_view(), name='catalog'),
    path('sub_catalog/<str:sub_catalog_name>/<str:current_item_type>/<str:prev_item_type>/',
         views.sub_catalog, name='sub_catalog'),
    path('item/<int:item_id>/<str:sub_catalog_name>/', views.item, name='item'),
]

store/home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.start, name='start'),
    path('section/<str:section_name>/<str:previous_section>/', views.section, name='section'),
]

store/store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('users/', include('users.urls')),
    path('catalog/', include('catalog.urls')),
    path('service/', include('service.urls')),
    path('car_wash/', include('car_wash.urls')),
    path('contacts/', include('contacts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/catalog/models.py
from django.db import models
from django.db.models import SET_NULL, PROTECT

from catalog.constants import HEAD, DUMP, CARGO, LIGHT, BRAKES, ENGINE

NULLABLE = {'null': True, 'blank': True}


class SubCatalog(models.Model):
    name = models.CharField(max_length=20, verbose_name='Name')
    label = models.CharField(max_length=20, verbose_name='Label')
    img = models.CharField(max_length=200)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Sub catalog'
        verbose_name_plural = 'Sub catalogs'
        ordering = ('-name',)


class Truck(models.Model):

    TRUCKS_TYPES = [
        (HEAD, 'head'),
        (CARGO, 'cargo'),
        (DUMP, 'dump'),
    ]

    name = models.CharField(max_length=50)
    price = models.IntegerField()
    info = models.OneToOneField('TruckInfo', on_delete=SET_NULL, **NULLABLE, related_name='truck')
    sub_catalog = models.ForeignKey('SubCatalog', on_delete=PROTECT, related_name='truck_sub_catalog')
    type = models.CharField(max_length=10, choices=TRUCKS_TYPES, **NULLABLE)
    main_photo = models.ImageField(upload_to='trucks_img/')
    second_photo = models.ImageField(upload_to='trucks_img/', **NULLABLE)
    third_photo = models.ImageField(upload_to='trucks_img/', **NULLABLE)
    create_date = models.DateField(auto_now_add=True)
    change_date = models.DateField(auto_now=True)

    def __str__(self):
        return f'{self.name} {self.type}'

    def show_id(self):
        return f'{self.pk:05}'

    class Meta:
        verbose_name = 'Truck'
        verbose_name_plural = 'Trucks'
        ordering = ('pk',)


class TruckInfo(models.Model):

    class Condition(models.IntegerChoices):
        BRAND_NEW = 0, 'brand new'
        USED = 1, 'used'

    year = models.IntegerField(**NULLABLE)
    mileage = models.IntegerField(**NULLABLE)
    power = models.IntegerField(**NULLABLE)
    condition = models.BooleanField(choices=Condition.choices)
    discount = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'TruckInfo'
        verbose_name_plural = 'TruckInfo'


class Part(models.Model):

    PARTS_TYPES = [
        (LIGHT, 'light'),
        (ENGINE, 'engine'),
        (BRAKES, 'brakes'),
    ]

    name = models.CharField(max_length=50)
    price = models.IntegerField()
    info = models.TextField(**NULLABLE)
    sub_catalog = models.ForeignKey('SubCatalog', on_delete=PROTECT, related_name='part_sub_catalog')
    type = models.CharField(max_length=10, choices=PARTS_TYPES, **NULLABLE)
    main_photo = models.ImageField(upload_to='parts_img/')
    create_date = models.DateField(auto_now_add=True)
    change_date = models.DateField(auto_now=True)

    class Meta:
        verbose_name = 'Part'
        verbose_name_plural = 'Parts'
        ordering = ('pk',)

store/catalog/views.py
from django.core.paginator import Paginator
from django.shortcuts import render
from django.views import View
from django.views.generic import TemplateView

from catalog.constants import ITEMS_TYPES_DATA, SUB_CATALOG_CONTEXT, SUB_CATALOG_TEMPLATES
from catalog.models import Truck, Part
from catalog.templatetags.catalog_tags import get_catalog_items


def catalog(request):
    return render(request, 'catalog/catalog.html')


class Catalog(TemplateView):
    template_name = 'catalog/catalog.html'


def sub_catalog(request, sub_catalog_name, current_item_type, prev_item_type):
    # current_item_type = request.GET.get('current_item_type', 'all types')
    # prev_item_type = request.GET.get('prev_item_type', 'all types')
    page = request.GET.get('page', 1)
    items = get_catalog_items(sub_catalog_name, current_item_type)
    paginator = Paginator(items, 6)
    current_page = paginator.page(int(page))

    context = {
        'sub_catalog_name': sub_catalog_name,
        'types_data': ITEMS_TYPES_DATA[sub_catalog_name],
        'current_item_type': current_item_type,
        'prev_item_type': prev_item_type,
        'items': current_page,
    }
    return render(request, 'catalog/sub_catalog.html', {**context, **SUB_CATALOG_CONTEXT})


def item(request, item_id, sub_catalog_name):
    CATALOG_TABLES = {'trucks': Truck, 'parts': Part}
    catalog_item = CATALOG_TABLES[sub_catalog_name].objects.get(pk=item_id)
    context = {
        'item': catalog_item,
    }
    return render(request, SUB_CATALOG_TEMPLATES[sub_catalog_name], {**context, **SUB_CATALOG_CONTEXT})

store/catalog/templates/catalog/catalog.html
{% extends 'base.html' %}
{% load static %}
{% load catalog_tags %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'css/catalog.css' %}">
{% endblock %}

{% block content %}
    <div class="sub-catalogs">
        {% get_sub_catalogs as sub_catalogs %}
        {% for sub_catalog in sub_catalogs %}
        <a class="sub-catalog-link"
            href="{% url 'catalog:sub_catalog' sub_catalog.name 'all types' 'all types' %}">
            <div class="sub-catalog" style='background-image:url("{% static sub_catalog.img %}");'>
                <div class="sub-catalog-label">{{ sub_catalog.label|upper }}</div>
            </div>
        </a>
        {% endfor %}
    </div>
{% endblock %}

store/catalog/templates/catalog/item.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'css/item.css' %}">
{% endblock %}

{% block content %}
<div class="flex-container">
    <div class="main-info-block">
        <div>
            {% block photo %}{% endblock %}
        </div>

        <div class="item-info">
            {% block info %}{% endblock %}
        </div>
    </div>

    <div class="right-bar">
        {% block right_bar %}{% endblock %}
    </div>
</div>
{% endblock %}

store/catalog/templates/catalog/part_item.html
{% extends 'catalog/item.html' %}

{% block photo %}
    <img class="photo" src="{{ item.main_photo.url }}">
{% endblock %}

{% block info %}
    <div class="item-name">{{ item.name }}: {{ item.price }} EUR</div>
{% endblock %}

{% block right_bar %}
    <div class="right-bar-content">description:</div>
{% endblock %}

store/catalog/templates/catalog/sub_catalog.html
{% extends 'base.html' %}
{% load static %}
{% load sections_tags %}
{% load catalog_tags %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'css/content_background.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/sub_catalog.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/pagination.css' %}">
{% endblock %}

{% block content %}
<div class="store-window">
    <div class="left-bar">
        <img id="target" class="types_cursor" src="{% static 'img/types_cursor.png' %}" alt="types cursor">

        {% block types %}
            {% for type_data in types_data %}
            <map name="item_link_{{ type_data.name }}">
                {% if type_data.name == current_item_type %}
                    <area id="active"/>
                {% else %}
                    <area id="{% if type_data.name == prev_item_type %}prev{% else %}usual{% endif %}"
                          href="{% url 'catalog:sub_catalog' sub_catalog_name type_data.name current_item_type %}"
                          shape="rect" coords="20, 60, 140, 100" />
                {% endif %}
            </map>

            <img usemap="#item_link_{{ type_data.name }}" class="type-icon"
                 src="{% static type_data.icon %}" alt="{{ type_data.name }} icon">
            {% endfor %}
        {% endblock %}

        {% include 'catalog/includes/call_us.html' %}
    </div>

    <div class="scroll-container">
        <div class="store-items">
            {% for item in items %}
                {% include 'catalog/includes/container_item.html' %}
            {% endfor %}

            {% if items.paginator.num_pages > 1 %}
                {% include 'catalog/includes/pagination.html' %}
            {% else %}
                <p>no items</p>
            {% endif %}
        </div>
    </div>
</div>

<script>
    var target = document.getElementById("target");
    var prev = document.getElementById("prev");
    var yPositionPrev = prev.offsetTop;
    target.style['top'] = yPositionPrev + "px";

    var currentType = document.getElementById("active");
    var startPosition = currentType.offsetTop;
    target.style.top = startPosition + "px";
</script>
{% endblock %}

store/catalog/templates/catalog/truck_item.html
{% extends 'catalog/item.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'css/item.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/carousel.css' %}">
{% endblock %}

{% block photo %}
<div class="slider-container">
    <a class="prev" onclick="plusSlides(-1)"><img class="left-arrow" src="{% static 'img/left_arrow.png' %}"></a>

    <div class="slider">
        <div class="frame">
             <img class="slider-photo" src="{{ item.main_photo.url }}">
        </div>
        {% if item.second_photo %}
        <div class="frame">
             <img class="slider-photo" src="{{ item.second_photo.url }}">
        </div>
        {% endif %}
        {% if item.third_photo %}
        <div class="frame">
             <img class="slider-photo" src="{{ item.third_photo.url }}">
        </div>
        {% endif %}
    </div>

    <a class="next" onclick="plusSlides(1)"><img class="right-arrow" src="{% static 'img/right_arrow.png' %}"></a>
</div>

<script src="{% static 'js/carousel.js' %}"></script>
{% endblock %}

{% block info %}
    <div class="item-name">{{ item.name }} {{ item.info.year }}</div>
    <div style="margin-bottom:0.5em;display:flex;justify-content:center;">
        <div style="text-align:right;">
            mileage<br>
            power<br>
            price<br>
        </div>
        <div><pre>   |   </pre><pre>   |   </pre><pre>   |   </pre></div>
        <div style="text-align:left;">
            {{ item.info.mileage }}<br>
            {{ item.info.power }}<br>
            {{ item.price }} EUR<br>
        </div>
    </div>
{% endblock %}

{% block right_bar %}
    <div class="right-bar-content">maybe one of these:</div>
{% endblock %}