store/home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.start, name='start'),
    path('section/<str:section_name>/<str:previous_section>/', views.section, name='section'),
]

store/store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('users/', include('users.urls')),
    path('catalog/', include('catalog.urls')),
    path('service/', include('service.urls')),
    path('car_wash/', include('car_wash.urls')),
    path('contacts/', include('contacts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/users/urls.py
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('', views.CustomLoginView.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register_user, name='register'),
]

store/templates/base.html
{% load static %}
{% load sections_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link rel="shortcut icon" href="{% static 'img/icon.svg' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/null_style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/content_background.css' %}">
    {% block style %}{% endblock %}
</head>

<body>
    <div class="grid-container">
        <div class="side-bar">
            <img class="man-logo" src="{% static 'img/logo_man.png' %}">
            <p class="truck-store">TRUCK STORE</p>

            <div class="side-bar-navigation">
                <nav>
                    {% get_sections as sections %}
                    {% for section in sections %}
                        {% if section == section_name and is_sub_section %}
                            <a href="{% url 'home:section' section section_name %}">
                                <div class="side-bar-below-current-button">{{ section_name }}</div>
                            </a>
                        {% elif section == section_name %}
                            <div class="side-bar-current-button">{{ section }}</div>
                        {% else %}
                            <a href="{% url 'home:section' section section_name %}">
                                <div class="side-bar-button">{{ section }}</div>
                            </a>
                        {% endif %}
                    {% endfor %}
                </nav>

                <div class="low-message"><pre><sup>*</sup>not an official<br> dealership</pre></div>
            </div>
        </div>

        {% if previous_section != 'main page' and section_name == 'main page' %}<div class="to_main_page">
        {% elif previous_section == 'main page' and section_name != 'main page' %}<div class="content">
        {% elif previous_section != 'main page' and section_name != 'main page' %}<div class="not_main_page">
        {% endif %}

            <header>
                <div class="auth-buttons">
                    <div class="left-side">
                        {% if user.is_authenticated %}
                            <p>user email: <span class="username">{{ user.email }}</span></p>
                        {% else %}
                            <a href="{% url 'users:register' %}">SIGN UP</a>
                        {% endif %}
                    </div>
                    <pre> | </pre>
                    <div class="right-side">
                        {% if user.is_authenticated %}
                            <a href="{% url 'users:logout' %}">LOGOUT</a>
                        {% else %}
                            <a href="{% url 'users:login' %}">SIGN IN</a>
                        {% endif %}
                    </div>
                </div>
            </header>

            {% block content %}{% endblock %}

            <footer>
                <div class="developer-contact">
                    <a href="https://t.me/elcapitansmetankins" target="_blank">
                        <img class="logo-telegram" src="{% static 'img/logo-telegram.svg' %}" alt="logo Telegram">
                    </a>
                    <a href="https://t.me/elcapitansmetankins" target="_blank">
                        <div class="developer-contact-text">developer contact</div>
                    </a>
                </div>
            </footer>
        </div>
    </div>
</body>
</html>